"""Export the Stage C-2 Logistic Regression model and C/Python golden vectors."""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

ROOT_DIR = Path(__file__).resolve().parents[1]
PYTHON_DIR = ROOT_DIR / "python"
if str(PYTHON_DIR) not in sys.path:
    sys.path.insert(0, str(PYTHON_DIR))

from dataset_audit import audit_csv  # noqa: E402
from train_tiny_classifier import (  # noqa: E402
    CLASS_NAMES,
    CLASS_TO_INDEX,
    FEATURE_NAMES,
    RAW_DIR,
    WINDOW_SIZE,
    build_groups,
    extract_features,
    load_windows,
)

MODEL_DIR = ROOT_DIR / "firmware" / "stm32f103" / "MotorTinyML_F103" / "App" / "Model"
PARAMS_H = MODEL_DIR / "tiny_classifier_params.h"
PARAMS_C = MODEL_DIR / "tiny_classifier_params.c"
GOLDEN_PATH = ROOT_DIR / "dataset" / "reports" / "tiny_classifier_golden_vectors.txt"
REPORT_PATH = ROOT_DIR / "dataset" / "reports" / "tiny_classifier_stage_c2.txt"

FEATURE_COUNT = 21
CLASS_COUNT = 4
PARITY_TOLERANCES = (1e-3, 1e-3, 1e-3)


def c_formula_features(raw: np.ndarray) -> np.ndarray:
    """Reproduce the float32 accumulation order used by tiny_classifier.c."""
    output = np.empty(FEATURE_COUNT, dtype=np.float32)
    for axis in range(3):
        values = raw[:, axis].astype(np.float32)
        total = np.float32(0.0)
        sum_square = np.float32(0.0)
        minimum = np.float32(values[0])
        maximum = np.float32(values[0])
        for value in values:
            total = np.float32(total + value)
            sum_square = np.float32(sum_square + np.float32(value * value))
            minimum = np.minimum(minimum, value)
            maximum = np.maximum(maximum, value)
        mean = np.float32(total / np.float32(len(values)))
        variance_sum = np.float32(0.0)
        for value in values:
            delta = np.float32(value - mean)
            variance_sum = np.float32(variance_sum + np.float32(delta * delta))
        std = np.float32(np.sqrt(float(variance_sum / np.float32(len(values)))))
        rms = np.float32(np.sqrt(float(sum_square / np.float32(len(values)))))
        mad_sum = np.float32(0.0)
        for value in values:
            mad_sum = np.float32(mad_sum + np.float32(abs(float(value - mean))))
        base = axis * 7
        output[base:base + 7] = (mean, std, rms, minimum, maximum, maximum - minimum,
                                  np.float32(mad_sum / np.float32(len(values))))
    if not np.all(np.isfinite(output)):
        raise ValueError("C-formula feature extraction produced NaN or Inf values.")
    return output


def c_scaled_scores(features: np.ndarray, mean: np.ndarray, std: np.ndarray,
                    weights: np.ndarray, bias: np.ndarray) -> tuple[np.ndarray, np.ndarray, int]:
    scaled = np.asarray((features - mean) / std, dtype=np.float32)
    scores = np.empty(CLASS_COUNT, dtype=np.float32)
    for class_index in range(CLASS_COUNT):
        score = np.float32(bias[class_index])
        for feature_index in range(FEATURE_COUNT):
            score = np.float32(score + np.float32(weights[class_index, feature_index] * scaled[feature_index]))
        scores[class_index] = score
    if not np.all(np.isfinite(scaled)) or not np.all(np.isfinite(scores)):
        raise ValueError("C-formula scaling or scoring produced NaN or Inf values.")
    return scaled, scores, int(np.argmax(scores))


def c_float(value: float) -> str:
    return f"{float(np.float32(value)):.9g}f"


def write_params(mean: np.ndarray, std: np.ndarray, weights: np.ndarray, bias: np.ndarray,
                 params_h: Path, params_c: Path) -> None:
    params_h.parent.mkdir(parents=True, exist_ok=True)
    params_h.write_text(
        """#ifndef TINY_CLASSIFIER_PARAMS_H\n#define TINY_CLASSIFIER_PARAMS_H\n\n#include <stdint.h>\n\n#define TINY_CLASSIFIER_FEATURE_COUNT 21\n#define TINY_CLASSIFIER_CLASS_COUNT 4\n\n#ifdef __cplusplus\nextern \"C\" {\n#endif\n\nextern const float g_feature_mean[TINY_CLASSIFIER_FEATURE_COUNT];\nextern const float g_feature_std[TINY_CLASSIFIER_FEATURE_COUNT];\nextern const float g_logreg_weights[TINY_CLASSIFIER_CLASS_COUNT][TINY_CLASSIFIER_FEATURE_COUNT];\nextern const float g_logreg_bias[TINY_CLASSIFIER_CLASS_COUNT];\n\n/* Feature order: x/y/z mean, std, rms, min, max, peak_to_peak, mad. */\n/* Class order: 0 normal, 1 rotor_unbalance, 2 mechanical_looseness, 3 overload. */\n\n#ifdef __cplusplus\n}\n#endif\n\n#endif /* TINY_CLASSIFIER_PARAMS_H */\n""", encoding="utf-8"
    )
    lines = [
        '#include "tiny_classifier_params.h"',
        "",
        "/* Generated by python/export_tiny_classifier.py. Do not edit manually. */",
        "",
        "const float g_feature_mean[21] = {",
        "    " + ", ".join(c_float(value) for value in mean) + ",",
        "};",
        "const float g_feature_std[21] = {",
        "    " + ", ".join(c_float(value) for value in std) + ",",
        "};",
        "const float g_logreg_weights[4][21] = {",
    ]
    for row in weights:
        lines.append("    {" + ", ".join(c_float(value) for value in row) + "},")
    lines.extend([
        "};",
        "const float g_logreg_bias[4] = {",
        "    " + ", ".join(c_float(value) for value in bias) + ",",
        "};",
        "",
    ])
    params_c.write_text("\n".join(lines), encoding="utf-8")


def write_golden(vectors, mean, std, weights, bias, output_path: Path) -> tuple[float, float, float, bool]:
    lines = [
        "MotorTinyML Tiny Classifier Stage C-2 Golden Vectors",
        "feature_order: x_mean,x_std,x_rms,x_min,x_max,x_peak_to_peak,x_mad, then y and z",
        "class_order: 0 normal, 1 rotor_unbalance, 2 mechanical_looseness, 3 overload",
        "",
    ]
    feature_diff = scaled_diff = score_diff = 0.0
    class_agreement = True
    for class_name, path, raw in vectors:
        vectorized = extract_features(raw[None, ...])[0].astype(np.float32)
        c_features = c_formula_features(raw)
        scaled, scores, predicted = c_scaled_scores(c_features, mean, std, weights, bias)
        sklearn_scaled = np.asarray((vectorized - mean) / std, dtype=np.float32)
        sklearn_scores = np.asarray(np.asarray(weights, dtype=np.float32) @ sklearn_scaled + np.asarray(bias, dtype=np.float32), dtype=np.float32)
        if not np.all(np.isfinite(vectorized)):
            raise ValueError("Golden vector features contain NaN or Inf values.")
        feature_diff = max(feature_diff, float(np.max(np.abs(vectorized - c_features))))
        scaled_diff = max(scaled_diff, float(np.max(np.abs(sklearn_scaled - scaled))))
        score_diff = max(score_diff, float(np.max(np.abs(sklearn_scores - scores))))
        class_agreement = class_agreement and int(np.argmax(sklearn_scores)) == predicted
        lines.extend([
            f"[{class_name}] {path.name}",
            "raw_window[200][3]:",
        ])
        lines.extend("  " + ",".join(str(int(value)) for value in row) for row in raw)
        lines.extend([
            "expected_features[21]: " + ",".join(c_float(value) for value in c_features),
            "expected_scaled_features[21]: " + ",".join(c_float(value) for value in scaled),
            "expected_scores[4]: " + ",".join(c_float(value) for value in scores),
            f"expected_class: {predicted} ({CLASS_NAMES[predicted]})",
            "",
        ])
    tolerance_ok = feature_diff <= PARITY_TOLERANCES[0] and scaled_diff <= PARITY_TOLERANCES[1] and score_diff <= PARITY_TOLERANCES[2] and class_agreement
    lines.extend([
        "PC/C formula parity",
        f"feature_max_abs_diff: {feature_diff:.9g}",
        f"scaled_feature_max_abs_diff: {scaled_diff:.9g}",
        f"score_max_abs_diff: {score_diff:.9g}",
        f"predicted_class_agreement: {class_agreement}",
        f"parity_status: {'PASS' if tolerance_ok else 'FAIL'}",
    ])
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return feature_diff, scaled_diff, score_diff, tolerance_ok


def main() -> None:
    groups, warnings = build_groups(None)
    features_by_file = []
    labels = []
    for (class_name, _speed), files in sorted(groups.items()):
        for path in files:
            windows = load_windows(path)
            values = extract_features(windows)
            features_by_file.append(values)
            labels.extend([CLASS_TO_INDEX[class_name]] * len(values))
    features = np.concatenate(features_by_file).astype(np.float64)
    labels_array = np.asarray(labels, dtype=np.int64)
    mean = features.mean(axis=0)
    std = features.std(axis=0, ddof=0)
    std[std == 0] = 1.0
    scaled = (features - mean) / std
    if not np.all(np.isfinite(scaled)):
        raise SystemExit("Scaled training features contain NaN or Inf; export aborted.")
    model = LogisticRegression(max_iter=2000, solver="lbfgs", random_state=42)
    model.fit(scaled, labels_array)
    weights = np.asarray(model.coef_, dtype=np.float32)
    bias = np.asarray(model.intercept_, dtype=np.float32)
    mean32 = np.asarray(mean, dtype=np.float32)
    std32 = np.asarray(std, dtype=np.float32)
    for name, values in (("features", features), ("scaler mean", mean32), ("scaler std", std32),
                         ("weights", weights), ("bias", bias)):
        if not np.all(np.isfinite(values)):
            raise SystemExit(f"{name} contains NaN or Inf; export aborted.")

    temp_params_h = PARAMS_H.with_name(PARAMS_H.name + ".tmp")
    temp_params_c = PARAMS_C.with_name(PARAMS_C.name + ".tmp")
    temp_golden = GOLDEN_PATH.with_name(GOLDEN_PATH.name + ".tmp")
    for temporary in (temp_params_h, temp_params_c, temp_golden):
        temporary.unlink(missing_ok=True)
    write_params(mean32, std32, weights, bias, temp_params_h, temp_params_c)

    vectors = []
    for class_name in CLASS_NAMES:
        candidates = sorted(path for (name, _speed), files in groups.items() if name == class_name for path in files)
        path = candidates[0]
        vectors.append((class_name, path, load_windows(path)[0].astype(np.int16)))
    feature_diff, scaled_diff, score_diff, parity_ok = write_golden(
        vectors, mean32, std32, weights, bias, temp_golden
    )
    if not parity_ok:
        for temporary in (temp_params_h, temp_params_c, temp_golden):
            temporary.unlink(missing_ok=True)
        raise SystemExit("PC/C parity check failed; generated outputs must not be used.")

    temp_params_h.replace(PARAMS_H)
    temp_params_c.replace(PARAMS_C)
    temp_golden.replace(GOLDEN_PATH)

    train_predictions = model.predict(scaled)
    report = [
        "MotorTinyML Stage C-2 Tiny Classifier Export",
        "=" * 48,
        f"included_csv_count: {sum(len(files) for files in groups.values())}",
        f"included_window_count: {len(features)}",
        f"training_accuracy: {accuracy_score(labels_array, train_predictions):.6f} (not an independent test metric)",
        f"feature_count: {FEATURE_COUNT}",
        "feature_order: " + ", ".join(FEATURE_NAMES),
        "class_mapping: 0 normal, 1 rotor_unbalance, 2 mechanical_looseness, 3 overload",
        "std: population std (ddof=0)",
        "rms: sqrt(mean(x^2)); mad: mean(abs(x - mean))",
        "scaler_mean: " + ", ".join(c_float(value) for value in mean32),
        "scaler_std: " + ", ".join(c_float(value) for value in std32),
        "weights and bias: emitted to tiny_classifier_params.c",
        f"PC/C feature max abs diff: {feature_diff:.9g}",
        f"PC/C scaled feature max abs diff: {scaled_diff:.9g}",
        f"PC/C score max abs diff: {score_diff:.9g}",
        "PC/C parity: PASS",
        "C contract: raw int16_t[200][3] -> 21 float features -> scaled linear scores -> argmax",
        "No TensorFlow, TFLite, TFLite Micro, dynamic allocation, or softmax is required.",
        "Flash estimate: 88 float parameters + scaler arrays + code; typically well below a few KiB.",
        "RAM estimate: raw window 1200 bytes plus 21-feature/score working buffers.",
        "LORO reference: mean 0.9975, std 0.0035, mechanical_looseness recall 1.0000.",
        f"warnings: {warnings or 'none'}",
    ]
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(report) + "\n", encoding="utf-8")
    print(f"Generated: {PARAMS_H}")
    print(f"Generated: {PARAMS_C}")
    print(f"Generated: {GOLDEN_PATH}")
    print(f"Generated: {REPORT_PATH}")
    print("PC/C parity: PASS")


if __name__ == "__main__":
    main()
