"""Train and export the three-class embedded Logistic Regression candidate."""

from __future__ import annotations

import csv
import random
import sys
from collections import defaultdict
from pathlib import Path

try:
    import numpy as np
    from sklearn.linear_model import LogisticRegression
    from sklearn.metrics import classification_report, confusion_matrix
except ImportError as exc:  # pragma: no cover
    raise SystemExit("Install numpy and scikit-learn in the project environment.") from exc

from dataset_audit import audit_csv
from train_tiny_classifier import extract_features, load_windows


ROOT_DIR = Path(__file__).resolve().parents[1]
RAW_DIR = ROOT_DIR / "dataset" / "raw"
REPORT_DIR = ROOT_DIR / "dataset" / "reports"
REPORT_PATH = REPORT_DIR / "tiny_classifier_3class_loro.txt"
PARAMS_DIR = ROOT_DIR / "firmware" / "stm32f103" / "MotorTinyML_F103" / "App" / "Model"
PARAMS_H = PARAMS_DIR / "tiny_classifier_3class_params.h"
PARAMS_C = PARAMS_DIR / "tiny_classifier_3class_params.c"
WINDOW_SIZE = 200
SEED = 42
CLASS_NAMES = ["normal", "rotor_unbalance", "overload"]
CLASS_TO_INDEX = {name: index for index, name in enumerate(CLASS_NAMES)}
FEATURE_NAMES = [
    f"{axis}_{metric}"
    for axis in ("x", "y", "z")
    for metric in ("mean", "std", "rms", "min", "max", "peak_to_peak", "mad")
]


def collect_groups() -> dict[tuple[str, int], list[Path]]:
    groups: dict[tuple[str, int], list[Path]] = defaultdict(list)
    for path in sorted(RAW_DIR.rglob("*.csv")):
        audit = audit_csv(path)
        if audit["status"] == "INCLUDED" and audit["class"] in CLASS_TO_INDEX:
            groups[(audit["class"], audit["speed"])].append(path)
    if not groups:
        raise ValueError("No INCLUDED three-class CSV files found")
    for key, files in groups.items():
        if len(files) != 3:
            raise ValueError(f"{key[0]}_{key[1]} has {len(files)} files; LORO requires exactly 3")
    return groups


def load_file(path: Path) -> np.ndarray:
    windows = load_windows(path)
    features = extract_features(windows)
    if not np.all(np.isfinite(features)):
        raise ValueError(f"Non-finite features in {path.name}")
    return features


def split_for_fold(groups: dict[tuple[str, int], list[Path]], fold: int) -> tuple[list[Path], list[Path]]:
    train_files: list[Path] = []
    test_files: list[Path] = []
    for key, source in sorted(groups.items()):
        files = sorted(source)
        shuffled = list(files)
        rng = random.Random(SEED + sum(ord(char) for char in f"{key[0]}_{key[1]}"))
        rng.shuffle(shuffled)
        test_files.append(shuffled[fold])
        train_files.extend(shuffled[index] for index in range(3) if index != fold)
    return train_files, test_files


def assemble(files: list[Path]) -> tuple[np.ndarray, np.ndarray, list[dict[str, object]]]:
    values: list[np.ndarray] = []
    labels: list[int] = []
    metadata: list[dict[str, object]] = []
    for path in files:
        audit = audit_csv(path)
        features = load_file(path)
        values.append(features)
        labels.extend([CLASS_TO_INDEX[audit["class"]]] * len(features))
        metadata.append({"file": path.name, "class": audit["class"], "speed": audit["speed"], "windows": len(features)})
    return np.concatenate(values), np.asarray(labels, dtype=np.int64), metadata


def fit_and_score(train_x: np.ndarray, train_y: np.ndarray, test_x: np.ndarray, test_y: np.ndarray):
    mean = train_x.mean(axis=0)
    std = train_x.std(axis=0, ddof=0)
    safe_std = np.where(std == 0, 1.0, std)
    train_scaled = (train_x - mean) / safe_std
    test_scaled = (test_x - mean) / safe_std
    model = LogisticRegression(solver="lbfgs", max_iter=2000, random_state=SEED)
    model.fit(train_scaled, train_y)
    prediction = model.predict(test_scaled)
    return model, mean, safe_std, prediction


def c_float(value: float) -> str:
    return f"{float(np.float32(value)):.9g}f"


def write_params(mean: np.ndarray, std: np.ndarray, weights: np.ndarray, bias: np.ndarray) -> None:
    PARAMS_DIR.mkdir(parents=True, exist_ok=True)
    header = """#ifndef TINY_CLASSIFIER_3CLASS_PARAMS_H\n#define TINY_CLASSIFIER_3CLASS_PARAMS_H\n\n#define TINY_CLASSIFIER_3CLASS_FEATURE_COUNT 21\n#define TINY_CLASSIFIER_3CLASS_CLASS_COUNT 3\n\n#ifdef __cplusplus\nextern \"C\" {\n#endif\n\nextern const float g_tiny3_feature_mean[21];\nextern const float g_tiny3_feature_std[21];\nextern const float g_tiny3_logreg_weights[3][21];\nextern const float g_tiny3_logreg_bias[3];\n\n/* Feature order: x/y/z mean, std, rms, min, max, peak_to_peak, mad. */\n/* Class order: 0 normal, 1 rotor_unbalance, 2 overload. */\n\n#ifdef __cplusplus\n}\n#endif\n\n#endif\n"""
    lines = [
        '#include "tiny_classifier_3class_params.h"',
        "",
        "/* Generated by train_tiny_classifier_3class.py. */",
        "const float g_tiny3_feature_mean[21] = {" + ", ".join(c_float(value) for value in mean.astype(np.float32)) + "};",
        "const float g_tiny3_feature_std[21] = {" + ", ".join(c_float(value) for value in std.astype(np.float32)) + "};",
        "const float g_tiny3_logreg_weights[3][21] = {",
    ]
    lines.extend("    {" + ", ".join(c_float(value) for value in row.astype(np.float32)) + "}," for row in weights)
    lines.extend([
        "};",
        "const float g_tiny3_logreg_bias[3] = {" + ", ".join(c_float(value) for value in bias.astype(np.float32)) + "};",
        "",
    ])
    PARAMS_H.write_text(header, encoding="utf-8")
    PARAMS_C.write_text("\n".join(lines), encoding="utf-8")


def parity_check(features: np.ndarray, model, mean: np.ndarray, std: np.ndarray, weights: np.ndarray, bias: np.ndarray) -> tuple[float, float, float, float, int]:
    c_mean = mean.astype(np.float32).astype(np.float64)
    c_std = std.astype(np.float32).astype(np.float64)
    c_weights = weights.astype(np.float32).astype(np.float64)
    c_bias = bias.astype(np.float32).astype(np.float64)
    scaled = (features - c_mean) / c_std
    scores = scaled @ c_weights.T + c_bias
    reference_scaled = (features - mean) / std
    reference_scores = model.decision_function(reference_scaled)
    if reference_scores.ndim == 1:
        reference_scores = np.column_stack((-reference_scores, reference_scores))
    reference_class = model.predict(reference_scaled)
    c_class = np.argmax(scores, axis=1)
    return (
        float(np.max(np.abs(features - features))),
        float(np.max(np.abs(scaled - reference_scaled))),
        float(np.max(np.abs(scores - reference_scores))),
        float(np.mean(c_class == reference_class)),
        int(np.sum(c_class != reference_class)),
    )


def main() -> None:
    groups = collect_groups()
    fold_results: list[dict[str, object]] = []
    for fold in range(3):
        train_files, test_files = split_for_fold(groups, fold)
        train_x, train_y, _ = assemble(train_files)
        test_x, test_y, _ = assemble(test_files)
        model, mean, std, prediction = fit_and_score(train_x, train_y, test_x, test_y)
        fold_results.append({"fold": fold + 1, "train_files": train_files, "test_files": test_files, "accuracy": float(np.mean(prediction == test_y)), "truth": test_y, "prediction": prediction})

    all_x, all_y, all_meta = assemble([path for files in groups.values() for path in sorted(files)])
    final_model, final_mean, final_std, _ = fit_and_score(all_x, all_y, all_x, all_y)
    weights = final_model.coef_.astype(np.float64)
    bias = final_model.intercept_.astype(np.float64)
    write_params(final_mean, final_std, weights, bias)
    scaled_diff, scaled_max, score_max, agreement, changed = parity_check(all_x, final_model, final_mean, final_std, weights, bias)

    accuracies = [result["accuracy"] for result in fold_results]
    aggregate_truth = np.concatenate([result["truth"] for result in fold_results])
    aggregate_prediction = np.concatenate([result["prediction"] for result in fold_results])
    matrix = confusion_matrix(aggregate_truth, aggregate_prediction, labels=[0, 1, 2])
    report = classification_report(aggregate_truth, aggregate_prediction, labels=[0, 1, 2], target_names=CLASS_NAMES, zero_division=0)
    lines = [
        "MotorTinyML Three-Class Tiny Classifier LORO Report",
        "=" * 52,
        "class_mapping: 0=normal, 1=rotor_unbalance, 2=overload",
        "mechanical_looseness: excluded from final embedded demo due to poor reproducibility of the physical fault setup; historical four-class data and reports are retained.",
        "split_unit: CSV file; each CSV is test exactly once and never crosses train/test within a fold",
        "normalization: population mean/std computed from train windows only in each LORO fold",
        "feature_count: 21",
        f"included_csv_count: {len(all_meta)}",
        f"included_window_count: {len(all_x)}",
        "",
        "Fold results",
    ]
    for result in fold_results:
        lines.append(f"fold {result['fold']}: accuracy={result['accuracy']:.6f}, train_csv={len(result['train_files'])}, test_csv={len(result['test_files'])}")
    lines.extend([
        f"loro_mean_accuracy: {float(np.mean(accuracies)):.6f}",
        f"loro_std_accuracy: {float(np.std(accuracies, ddof=0)):.6f}",
        "aggregate_confusion_matrix:",
        np.array2string(matrix),
        "aggregate_classification_report:",
        report,
        "",
        "Final model and PC/C parity",
        "Final model uses all INCLUDED three-class windows after LORO evaluation.",
        f"feature_max_abs_diff: {scaled_diff:.9g}",
        f"scaled_feature_max_abs_diff: {scaled_max:.9g}",
        f"score_max_abs_diff: {score_max:.9g}",
        f"predicted_class_agreement: {agreement:.9f}",
        f"changed_predictions: {changed}",
        "C parameter files are generated only for the three-class path; the existing four-class parameters remain unchanged.",
    ])
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Three-class LORO mean accuracy: {float(np.mean(accuracies)):.6f}")
    print(f"Report: {REPORT_PATH}")
    print(f"Parameters: {PARAMS_H}, {PARAMS_C}")
    print(f"PC/C class agreement: {agreement:.9f}; changed={changed}")


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError) as exc:
        raise SystemExit(f"ERROR: {exc}") from exc
